name: redacted
description: Generate a loading widget using only an extension.
version: 0.0.5
homepage: https://github.com/mhdmoh/redacted

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  measure_size: ^4.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
